---

nginx_vhosts:
  - listen: "80"
    server_name: "blacklight.box"
    root: "/vagrant/blacklight"
    index: "index.php index.html index.htm"
    access_log: "/var/log/nginx/blacklight_project_access.log"
    error_log: "/var/log/nginx/blacklight_project_error.log"
    extra_parameters: |
      location / {
        proxy_pass         http://127.0.0.1:3000/;
        proxy_redirect     off;

        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
      }
  - listen: "80"
    server_name: "foobar.box"
    root: "/vagrant/foobar"
    index: "index.php index.html index.htm"
    access_log: "/var/log/nginx/blacklight_project_access.log"
    error_log: "/var/log/nginx/blacklight_project_error.log"
    extra_parameters: |
      location / {
        proxy_pass         http://127.0.0.1:3000/;
        proxy_redirect     off;

        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
      }