---

vagrant_box: blacklight-xenial32
vagrant_box_url: file://packer/build/blacklight-xenial32.box

vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
vagrant_gui: false

# If you need to run multiple instances of Blacklight Box VM,
# set a unique hostname, machine name, and IP address for 
# each instance.
vagrant_hostname: blacklight.box
vagrant_machine_name: blacklightbox
vagrant_ip: 192.168.2.160

# Allow Blacklight Box VM to be accessed via a public network
# Allow Blacklight Box VM to be accessed via a public network
# interface on your host. Vagrant boxes are insecure by default, 
# so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders:
  # The first synced folder will be used for the default Project Blacklight installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the blacklight folder.
  - local_path: .
    destination: /vagrant
    type: nfs
create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 1

# Ensure vagrant plugins are installed.
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater

# Minimum required versions.
blacklightbox_vagrant_version_min: '1.8.6'

# Domain names
blacklight_domain: blacklight.box

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. 
nginx_hosts:
  - server_name: "{{ blacklight_domain }} www.{{ blacklight_domain }}"
