---

- src: git+https://github.com/geerlingguy/ansible-role-git.git
  version: "2.0.3"
  name: geerlingguy.git

- src: git+https://github.com/geerlingguy/ansible-role-nginx.git
  version: "master"
  name: geerlingguy.nginx

- src: git+https://github.com/geerlingguy/ansible-role-java
  version: "1.9.5"
  name: geerlingguy.java

- src: git+https://github.com/rvm/rvm1-ansible
  version: "v2.1.2"
  name: rvm.ruby