---
# tasks file for datahub.blacklight

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - python-software-properties
    - libffi-dev

